<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ADUL7BM" failures="1" tests="6" name="Practice.Test.InvoiceTest2" time="55.518" errors="0" timestamp="12 Aug 2024 12:26:45 GMT" skipped="5">
  <testcase classname="Practice.Test.InvoiceTest2" name="createInvoiceTest2" time="9.307">
    <skipped/>
  </testcase> <!-- createInvoiceTest2 -->
  <testcase classname="Practice.Test.InvoiceTest2" name="createInvoiceTest2" time="9.115">
    <skipped/>
  </testcase> <!-- createInvoiceTest2 -->
  <testcase classname="Practice.Test.InvoiceTest2" name="createInvoiceTest2" time="9.015">
    <skipped/>
  </testcase> <!-- createInvoiceTest2 -->
  <testcase classname="Practice.Test.InvoiceTest2" name="createInvoiceTest2" time="10.068">
    <skipped/>
  </testcase> <!-- createInvoiceTest2 -->
  <testcase classname="Practice.Test.InvoiceTest2" name="createInvoiceTest2" time="9.032">
    <skipped/>
  </testcase> <!-- createInvoiceTest2 -->
  <testcase classname="Practice.Test.InvoiceTest2" name="createInvoiceTest2" time="8.981">
    <failure message="expected [Login] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Login] but found [Administrator - Home - vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Practice.Test.InvoiceTest2.createInvoiceTest2(InvoiceTest2.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- createInvoiceTest2 -->
</testsuite> <!-- Practice.Test.InvoiceTest2 -->
